{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.image.tag }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ template "name" . }}
spec:
  hosts:
  {{- toYaml .Values.ingress.hosts | nindent 2 }}
  gateways:
  - platform-services-gateway.default.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: {{ .Values.ingress.uriPrefix }}
    rewrite:
        uri: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ template "name" . }}
{{- end }}
