{{- if .Values.jwt_policy.enabled }}
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: {{ template "name" . }}-jwt
spec:
  targets:
  - name: {{ template "name" . }}
  {{- if .Values.jwt_policy.mtls }}
  peers:
  - mtls: {}
  {{- end }}
  origins:
  {{- range .Values.jwt_policy.identity }}
  - jwt:
      {{- if .audience }}
      audiences:
      - {{ .audience }}
      {{- end }}
      issuer: {{ .issuer }}
      jwksUri: {{ .uri }}
      {{- if or .excluded_path .included_path }}
      trigger_rules:
      {{- if .excluded_path }}
      - excluded_paths:
        {{- if .excluded_path.exact }}
        - exact: {{ .excluded_path.exact }}
        {{- end }}
        {{- if .excluded_path.prefix }}
        - prefix: {{ .excluded_path.prefix }}
        {{- end }}
      {{- end }}
      {{- if .included_path }}
      - included_paths:
        - exact: {{ .included_path }}
      {{- end }}
      {{- end }}
  {{- end }}
  principalBinding: USE_ORIGIN
{{- end }}
