{{- if .Values.image.pullSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}-registry-auth
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
{{- end -}}
